CREATE TABLE NPLPlayers (
    Player VARCHAR(120),
    Price_in_lakh DECIMAL(10, 2),
    Type VARCHAR(50),
    Acquisition VARCHAR(50),
    Role VARCHAR(50),
    Team VARCHAR(100)
);

-- Insert all NPL 2024 players with rumored prices (in Lakh NPR)
INSERT INTO NPLPlayers (Player, Price_in_lakh, Type, Acquisition, Role, Team) VALUES
('Sandeep Lamichhane', 20.00, 'Domestic', 'Marquee (Est.)', 'Bowler', 'Biratnagar Kings'),
('Lokesh Bam', 15.00, 'Domestic', 'Auction', 'Wicketkeeper', 'Biratnagar Kings'),
('Pratish GC', 15.00, 'Domestic', 'Auction', 'Bowler', 'Biratnagar Kings'),
('Bashir Ahmad', 10.00, 'Domestic', 'Auction', 'Batsman', 'Biratnagar Kings'),
('Rajesh Pulami Magar', 5.00, 'Domestic', 'Auction', 'All-rounder', 'Biratnagar Kings'),
('Jitendra Kumar Mukhiya', 5.00, 'Domestic', 'Auction', 'Bowler', 'Biratnagar Kings'),
('Anil Kharel', 5.00, 'Domestic', 'Auction', 'Bowler', 'Biratnagar Kings'),
('Dipak Bohara', 5.00, 'Domestic', 'Auction', 'Bowler', 'Biratnagar Kings'),
('Subash Bhandari', 2.50, 'Domestic', 'Auction', 'All-rounder', 'Biratnagar Kings'),
('Naren Bhatta', 2.00, 'Domestic', 'Auction', 'Bowler', 'Biratnagar Kings'),
('Mrinal Gurung', 2.00, 'Domestic', 'Auction', 'All-rounder', 'Biratnagar Kings'),
('Martin Guptill', 50.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Biratnagar Kings'),
('Nicholas Kirton', 8.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Biratnagar Kings'),
('Aqib Ilyas', 10.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Biratnagar Kings'),
('Chris Sole', 12.00, 'Overseas', 'Direct (Est.)', 'Bowler', 'Biratnagar Kings'),
('Scott Edwards', 15.00, 'Overseas', 'Direct (Est.)', 'Wicketkeeper', 'Biratnagar Kings'),
('Ismat Alam', 5.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Biratnagar Kings'),

('Kushal Malla', 20.00, 'Domestic', 'Marquee (Est.)', 'All-rounder', 'Chitwan Rhinos'),
('Rijan Dhakal', 10.00, 'Domestic', 'Auction', 'Bowler', 'Chitwan Rhinos'),
('Kamal Singh Airee', 10.00, 'Domestic', 'Auction', 'All-rounder', 'Chitwan Rhinos'),
('Sharad Vesawkar', 10.00, 'Domestic', 'Auction', 'All-rounder', 'Chitwan Rhinos'),
('Bipin Rawal', 8.00, 'Domestic', 'Auction', 'Wicketkeeper', 'Chitwan Rhinos'),
('Santosh Karki', 5.00, 'Domestic', 'Auction', 'Bowler', 'Chitwan Rhinos'),
('Dipesh Shrestha', 5.00, 'Domestic', 'Auction', 'All-rounder', 'Chitwan Rhinos'),
('Amar Singh Rautela', 5.00, 'Domestic', 'Auction', 'All-rounder', 'Chitwan Rhinos'),
('Deepak Bohara', 5.00, 'Domestic', 'Auction', 'Bowler', 'Chitwan Rhinos'),
('Ranjeet Kumar', 3.00, 'Domestic', 'Auction', 'All-rounder', 'Chitwan Rhinos'),
('Gautam KC', 2.00, 'Domestic', 'Auction', 'Batsman', 'Chitwan Rhinos'),
('Ravi Bopara', 40.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Chitwan Rhinos'),
('Sohail Tanvir', 25.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Chitwan Rhinos'),
('Marchant de Lange', 20.00, 'Overseas', 'Direct (Est.)', 'Bowler', 'Chitwan Rhinos'),
('Jan Nicol Loftie-Eaton', 15.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Chitwan Rhinos'),
('Luc Benkenstein', 10.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Chitwan Rhinos'),
('Basil Hameed', 12.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Chitwan Rhinos'),
('Hassan Eisakhil', 8.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Chitwan Rhinos'),

('Aasif Sheikh', 20.00, 'Domestic', 'Marquee (Est.)', 'Wicketkeeper-Batsman', 'Janakpur Bolts'),
('Lalit Rajbanshi', 15.00, 'Domestic', 'Auction', 'Bowler', 'Janakpur Bolts'),
('Anil Sah', 15.00, 'Domestic', 'Auction', 'Wicketkeeper-Batsman', 'Janakpur Bolts'),
('Rupesh K Singh', 0.00, 'Domestic', 'Iconic', 'Bowler', 'Janakpur Bolts'),
('Kishore Mahato', 10.00, 'Domestic', 'Auction', 'Bowler', 'Janakpur Bolts'),
('Aakash Tripathi', 10.00, 'Domestic', 'Auction', 'All-rounder', 'Janakpur Bolts'),
('Shubh Kansakar', 5.00, 'Domestic', 'Auction', 'Wicketkeeper', 'Janakpur Bolts'),
('Sher Malla', 5.00, 'Domestic', 'Auction', 'All-rounder', 'Janakpur Bolts'),
('Hemant Dhami', 5.00, 'Domestic', 'Auction', 'Batsman', 'Janakpur Bolts'),
('Arniko Prasad Yadav', 2.25, 'Domestic', 'Auction', 'Batsman', 'Janakpur Bolts'),
('Tul Bahadur Thapa Magar', 0.00, 'Domestic', 'Iconic', 'Bowler', 'Janakpur Bolts'),
('James Neesham', 45.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Janakpur Bolts'),
('Sohaib Maqsood', 20.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Janakpur Bolts'),
('Lahiru Milantha', 15.00, 'Overseas', 'Direct (Est.)', 'Wicketkeeper-Batsman', 'Janakpur Bolts'),
('Mohammad Mohsin', 12.00, 'Overseas', 'Direct (Est.)', 'Bowler', 'Janakpur Bolts'),
('Joshua Tromp', 10.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Janakpur Bolts'),
('Ben Mike', 18.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Janakpur Bolts'),

('Sompal Kami', 20.00, 'Domestic', 'Marquee (Est.)', 'All-rounder', 'Karnali Yaks'),
('Gulshan Jha', 15.00, 'Domestic', 'Auction', 'All-rounder', 'Karnali Yaks'),
('Deepak Dumre', 0.00, 'Domestic', 'Iconic', 'Wicketkeeper', 'Karnali Yaks'),
('Arjun Gharti', 0.00, 'Domestic', 'Iconic', 'Wicketkeeper', 'Karnali Yaks'),
('Dev Khanal', 2.00, 'Domestic', 'Auction', 'Batsman', 'Karnali Yaks'),
('Bhuvan Karki', 3.00, 'Domestic', 'Auction', 'Bowler', 'Karnali Yaks'),
('Dipendra Rawat', 5.00, 'Domestic', 'Auction', 'All-rounder', 'Karnali Yaks'),
('Bipin Sharma', 2.00, 'Domestic', 'Auction', 'Bowler', 'Karnali Yaks'),
('Unish Singh Thakuri', 2.00, 'Domestic', 'Auction', 'Batsman', 'Karnali Yaks'),
('Nandan Yadav', 2.00, 'Domestic', 'Auction', 'Batsman', 'Karnali Yaks'),
('Mousom Dhakal', 0.00, 'Domestic', 'Iconic', 'Bowler', 'Karnali Yaks'),
('Shikhar Dhawan', 80.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Karnali Yaks'),
('Babar Hayat', 25.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Karnali Yaks'),
('Hussain Talat', 30.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Karnali Yaks'),
('Zeeshan Maqsood', 15.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Karnali Yaks'),
('Jaykishan Kolsawala', 10.00, 'Overseas', 'Direct (Est.)', 'Bowler', 'Karnali Yaks'),
('Chadwick Walton', 20.00, 'Overseas', 'Direct (Est.)', 'Wicketkeeper', 'Karnali Yaks'),
('Will Bosisto', 18.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Karnali Yaks'),

('Karan KC', 20.00, 'Domestic', 'Marquee (Est.)', 'Bowler', 'Kathmandu Gurkhas'),
('Shahab Alam', 15.00, 'Domestic', 'Auction', 'Bowler', 'Kathmandu Gurkhas'),
('Bhim Sharki', 15.00, 'Domestic', 'Auction', 'Batsman', 'Kathmandu Gurkhas'),
('Dipesh Kandel', 0.00, 'Domestic', 'Iconic', 'Bowler', 'Kathmandu Gurkhas'),
('Pratik Shrestha', 3.00, 'Domestic', 'Auction', 'All-rounder', 'Kathmandu Gurkhas'),
('Shankar Rana', 2.00, 'Domestic', 'Auction', 'Batsman', 'Kathmandu Gurkhas'),
('Raju Rijal', 2.00, 'Domestic', 'Auction', 'Wicketkeeper', 'Kathmandu Gurkhas'),
('Bibek KC', 2.00, 'Domestic', 'Auction', 'Batsman', 'Kathmandu Gurkhas'),
('Krishna Karki', 2.00, 'Domestic', 'Auction', 'All-rounder', 'Kathmandu Gurkhas'),
('Krish Karki', 2.00, 'Domestic', 'Auction', 'Bowler', 'Kathmandu Gurkhas'),
('Rashid Khan', 70.00, 'Overseas', 'Direct (Est.)', 'Bowler', 'Kathmandu Gurkhas'),
('Stephen Eskinazi', 25.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Kathmandu Gurkhas'),
('Gerhard Erasmus', 20.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Kathmandu Gurkhas'),
('Dan Douthwaite', 15.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Kathmandu Gurkhas'),
('Michael Levitt', 12.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Kathmandu Gurkhas'),
('Nathan Sowter', 18.00, 'Overseas', 'Direct (Est.)', 'Bowler', 'Kathmandu Gurkhas'),

('Rohit Paudel', 20.00, 'Domestic', 'Marquee (Est.)', 'All-rounder', 'Lumbini Lions'),
('Surya Tamang', 15.00, 'Domestic', 'Auction', 'All-rounder', 'Lumbini Lions'),
('Bibek Yadav', 15.00, 'Domestic', 'Auction', 'All-rounder', 'Lumbini Lions'),
('Sundeep Jora', 15.00, 'Domestic', 'Auction', 'Batsman', 'Lumbini Lions'),
('Dinesh Adhikari', 5.00, 'Domestic', 'Auction', 'Bowler', 'Lumbini Lions'),
('Tilak Bhandari', 3.00, 'Domestic', 'Auction', 'All-rounder', 'Lumbini Lions'),
('Abhishesh Gautam', 2.00, 'Domestic', 'Auction', 'Batsman', 'Lumbini Lions'),
('Ashutosh Ghiraiya', 2.00, 'Domestic', 'Auction', 'Bowler', 'Lumbini Lions'),
('Durgesh Gupta', 2.00, 'Domestic', 'Auction', 'Bowler', 'Lumbini Lions'),
('Aarif Khan', 2.00, 'Domestic', 'Auction', 'All-rounder', 'Lumbini Lions'),
('Bikash Aagri', 0.00, 'Domestic', 'Iconic', 'Bowler', 'Lumbini Lions'),
('Arjun Saud', 0.00, 'Domestic', 'Iconic', 'Wicketkeeper', 'Lumbini Lions'),
('Ben Cutting', 30.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Lumbini Lions'),
('Unmukt Chand', 15.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Lumbini Lions'),
('Tom Moores', 20.00, 'Overseas', 'Direct (Est.)', 'Wicketkeeper', 'Lumbini Lions'),
('Ramon Simmonds', 12.00, 'Overseas', 'Direct (Est.)', 'Bowler', 'Lumbini Lions'),
('Saad Bin Zafar', 10.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Lumbini Lions'),

('Kushal Bhurtel', 20.00, 'Domestic', 'Marquee (Est.)', 'Batsman', 'Pokhara Avengers'),
('Sagar Dhakal', 15.00, 'Domestic', 'Auction', 'Bowler', 'Pokhara Avengers'),
('Aakash Chand', 15.00, 'Domestic', 'Auction', 'Bowler', 'Pokhara Avengers'),
('Sudip Aryal', 5.00, 'Domestic', 'Auction', 'Batsman', 'Pokhara Avengers'),
('Trit Raj Das', 3.00, 'Domestic', 'Auction', 'Bowler', 'Pokhara Avengers'),
('Sunam Gautam', 2.00, 'Domestic', 'Auction', 'Batsman', 'Pokhara Avengers'),
('Narayan Joshi', 2.00, 'Domestic', 'Auction', 'All-rounder', 'Pokhara Avengers'),
('Dinesh Kharel', 2.00, 'Domestic', 'Auction', 'Bowler', 'Pokhara Avengers'),
('Bipin Khatri', 2.00, 'Domestic', 'Auction', 'All-rounder', 'Pokhara Avengers'),
('Kiran Thagunna', 2.00, 'Domestic', 'Auction', 'Batsman', 'Pokhara Avengers'),
('Amrit Gurung', 0.00, 'Domestic', 'Iconic', 'All-rounder', 'Pokhara Avengers'),
('Bas de Leede', 35.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Pokhara Avengers'),
('Michael Leask', 25.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Pokhara Avengers'),
('Matt Critchley', 20.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Pokhara Avengers'),
('Andries Gous', 18.00, 'Overseas', 'Direct (Est.)', 'Wicketkeeper', 'Pokhara Avengers'),
('Anderson Phillip', 12.00, 'Overseas', 'Direct (Est.)', 'Bowler', 'Pokhara Avengers'),
('Raymon Reifer', 15.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Pokhara Avengers'),

('Dipendra Singh Airee', 20.00, 'Domestic', 'Marquee (Est.)', 'All-rounder', 'Sudurpaschim Royals'),
('Aarif Sheikh', 15.00, 'Domestic', 'Auction', 'Batsman', 'Sudurpaschim Royals'),
('Binod Bhandari', 0.00, 'Domestic', 'Iconic', 'Wicketkeeper', 'Sudurpaschim Royals'),
('Abinash Bohara', 5.00, 'Domestic', 'Auction', 'Bowler', 'Sudurpaschim Royals'),
('Khadak Bohora', 3.00, 'Domestic', 'Auction', 'All-rounder', 'Sudurpaschim Royals'),
('Naresh Budhayer', 2.00, 'Domestic', 'Auction', 'Batsman', 'Sudurpaschim Royals'),
('Basant Khatri', 2.00, 'Domestic', 'Auction', 'Bowler', 'Sudurpaschim Royals'),
('Arjun Kumal', 2.00, 'Domestic', 'Auction', 'Wicketkeeper', 'Sudurpaschim Royals'),
('Naren Saud', 2.00, 'Domestic', 'Auction', 'Batsman', 'Sudurpaschim Royals'),
('Amit Shrestha', 2.00, 'Domestic', 'Auction', 'All-rounder', 'Sudurpaschim Royals'),
('Bhoj Raj Bhatta', 0.00, 'Domestic', 'Iconic', 'All-rounder', 'Sudurpaschim Royals'),
('Ishan Pandey', 0.00, 'Domestic', 'Iconic', 'Bowler', 'Sudurpaschim Royals'),
('Scott Kuggeleijn', 25.00, 'Overseas', 'Direct (Est.)', 'Bowler', 'Sudurpaschim Royals'),
('Brandon McMullen', 15.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Sudurpaschim Royals'),
('Rohan Mustafa', 20.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Sudurpaschim Royals'),
('Saif Zaib', 18.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Sudurpaschim Royals'),
('Dilpreet Bajwa', 10.00, 'Overseas', 'Direct (Est.)', 'Batsman', 'Sudurpaschim Royals'),
('Harmeet Singh', 12.00, 'Overseas', 'Direct (Est.)', 'All-rounder', 'Sudurpaschim Royals');
